<template:extend view="template/default.phtml">
	<block:content>
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Surveys</h3>
				<div class="box-tools pull-right">
					<a class="btn btn-primary btn-sm" href="/survey/save"><i class="fa fa-plus"></i> New Survey</a>
				</div>
			</div>
			<div class="box-body">
				<table class="table table-condensed people">
					<thead>
						<th>ID</th> <th>Name</th> <th>Email Address</th>
					</thead>
					<?php if($surveys):?>
					<tbody>
						<?php foreach($survey as $i):?>
						<tr>
							<td><?=$i->id?></td>
							<td>
								<a href="/person/<?=$i->id?>">
									<?=$i->first_name . ' ' . $i->last_name?>
								</a>
							</td>
							<td><?=$i->email?></td>
						</tr>
						<?php endforeach;?>
					</tbody>
					<?php endif;?>
				</table>
			</div>
		</div>
	</block:content>	
</template:extend>