<template:extend view="template/default.phtml">
	<block:content>
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Surveys</h3>
				<div class="box-tools pull-right">
					<a class="btn btn-primary btn-sm" href="/survey/save"><i class="fa fa-plus"></i> New Survey</a>
				</div>
			</div>
			<div class="box-body">
				<?php if($surveys):?>
					<ul class="list-group">
						<?php foreach($surveys as $i):?>
						<li class="list-group-item">
							<a href="/survey/<?=$i->id?>"><?=$i->name?></a>
						</li>
						<?php endforeach; ?>
					</ul>
				<?php endif;?>
			</div>
		</div>
	</block:content>	
</template:extend>